### PR TITLE
Add key shortcut to open settings while in chat

### PR DESCRIPTION
**Pull request by waringer**

### CODE REVIEW

**Comment by BlayTheNinth** [comment]
The keybinds menu is way too stuffed with keybinds already, what does this offer over the existing two ways to get to the mod settings?

**Comment by waringer** [comment]
I have implemented it because i use the ChatTweaks together with the mod Macro / Keybind Mod. The problem is that booth mods shows a icon to configure at the lower right corner and the ChatTweaks config is not anymore available to me while i'm on a server (The Macro / Keybind Mod icon is on top of the ChatTweaks icon) and i don't want to leave the server to change the filters :(
Perhaps the default binding can be empty to not overload the default key bindings (I don't know to make it empty, sorry).

**Comment by BlayTheNinth** [comment]
You can access the mod options via ESC -> Mod Options -> Searching "Chat Tweaks" in the list and pressing the config button.

I don't think an empty binding is much better since it's in this weird state of most keys being required to type in the chat box. There's so much potential for user error and "hidden" limitations that it feels ugly.

**Comment by waringer** [comment]
The Mod Options is only in the Main Menu, while on a Server (in the pause menu) this options are not shown :(
But it's ok if you don't like the idea of a new keybinding. Perhaps you can then implement a config option to move the config button to the left of the chat line in the future, my Java skills are more or less not existing ;)

**Comment by BlayTheNinth** [comment]
image

There is a mod options button in the default pause menu, maybe you have another mod installed which put it somewhere else.

**Comment by waringer** [comment]
Oh, i'm sorry! Look like this is then a problem with my config :(
I thank you for your support and your great Mod!

**Pull request closed without merging**
